version: '2.1'

services:
  simple-java-project-master:
    image: simple-java-project-master
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3000:3000
      - 5005:5005
    